#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! First remove upstream configuration, then replace.
#! The initial removal is because the ytt `replace` operator
#! doesn't add any missing keys (a "replace-insert" feature has been requested).
#! To avoid the case when upstream changes occur that add or remove keys,
#! we just remove all of them and then in the next block, add them back in.

#@overlay/match by=overlay.subset({"kind":"ServiceAccount", "metadata":{"name":"external-dns"}})
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  #@overlay/remove
  annotations:

#@overlay/match by=overlay.subset({"kind":"ServiceAccount", "metadata":{"name":"external-dns"}})
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  #@ if/end data.values.serviceaccount.annotations:
  annotations: #@ data.values.serviceaccount.annotations
